services:
- type: web
  name: line-bot-python-on-render
  env: python
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn run:myapp
  plan: free
  autoDeploy: false
  envVars:
  - key: LINE_CHANNEL_ACCESS_TOKEN
    sync: false
  - key: LINE_CHANNEL_SECRET
    sync: false
